HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Account/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using AM.Application.Contracts;
using IM.Application.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SM.Application.Contracts;
using SM.Application.Contracts.Product;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public AccountSearchModel SearchModel { get; set; }
        public List<AccountViewModel> Accounts { get; set; }
        public SelectList RoleList { get; set; }
        private readonly IAccountApplication _accountApplication;
        public IndexModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            // RoleList = new SelectList(.GetList(), "Id", "Name");
            @ViewData["title"] = "Manage Accounts";
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {

            @ViewData["title"] = "Create a new Account";
            return Partial("./Create");
        }

        public JsonResult OnPostCreate(CreateAccount command)
        {
            var result = _accountApplication.Create(command);
            return new JsonResult(result);

        }

        public IActionResult OnGetEdit(long id)
        {
            @ViewData["title"] = "Account Management";
            var account = _accountApplication.GetDetail(id);
            return Partial("./Edit", account);
        }

        public JsonResult OnPostEdit(EditAccount command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var account = _accountApplication.getDetailforChangePassword(id);
            return Partial("./ChangePassword", account);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }


    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Account/Index.cshtml.cs
using System.Collections.Generic;
using AM.Application.Contracts.Account;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public AccountSearchModel SearchModel { get; set; }
        public List<AccountViewModel> Accounts { get; set; }
        public SelectList RoleList { get; set; }
        private readonly IAccountApplication _accountApplication;
        private readonly IRoleApplication _roleApplication;
        public IndexModel(IAccountApplication accountApplication,
            IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            RoleList = new SelectList(_roleApplication.GetAll(), "Id", "Name");
            @ViewData["title"] = "Manage Accounts";
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetRegister()
        {
            var command = new RegisterAccount
            {
                RoleList = _roleApplication.GetAll()
            };
            @ViewData["title"] = "Register a new Account";
            return Partial("./Register", command);
        }

        public JsonResult OnPostRegister(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            return new JsonResult(result);

        }

        public IActionResult OnGetEdit(long id)
        {
            @ViewData["title"] = "Account Management";
            var account = _accountApplication.GetDetail(id);
            account.RoleList = _roleApplication.GetAll();
            return Partial("./Edit", account);
        }

        public JsonResult OnPostEdit(EditAccount command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var account = _accountApplication.getDetailforChangePassword(id);
            return Partial("./ChangePassword", account);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }


    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Create.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Infrastructure;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        public List<SelectListItem> PermissionItems = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public CreateModel(IRoleApplication roleApplication,
            IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _exposers = permissionExposer;
        }

        public void OnGet()
        {
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermission = exposer.Exposer();
                foreach (var eachPermission in exposedPermission)
                {
                    var graoupName = new SelectListGroup
                    {
                        Name = eachPermission.Key
                    };
                    foreach (var permissionDetail in eachPermission.Value)
                    {
                        var item = new SelectListItem(permissionDetail.Name, permissionDetail.Code.ToString())
                        {
                            Group = graoupName
                        };
                        PermissionItems.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(CreateRole command)
        {

            var result = _roleApplication.Create(command);
            return RedirectToPage("Index");

        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public EditRole Role;
        public List<SelectListItem> PermissionItems = new List<SelectListItem>();
        public EditModel(IRoleApplication roleApplication,
            IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _exposers = permissionExposer;
        }

        public void OnGet(int id)
        {
            @ViewData["title"] = "Account Management";
            Role = _roleApplication.GetRole(id);
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermission = exposer.Exposer();
                foreach (var eachPermission in exposedPermission)
                {
                    var graoupName = new SelectListGroup
                    {
                        Name = eachPermission.Key
                    };
                    foreach (var permissionDetail in eachPermission.Value)
                    {
                        var item = new SelectListItem(permissionDetail.Name, permissionDetail.Code.ToString())
                        {
                            Group = graoupName
                        };
                        if (Role.MappedPermissions.Any(x => x.Code == permissionDetail.Code))
                            item.Selected = true;
                        PermissionItems.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(EditRole Role)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _roleApplication.Edit(Role);
            return RedirectToPage("Index");
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Index.cshtml.cs
using System.Collections.Generic;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public List<RoleViewModel> Roles { get; set; }
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
            @ViewData["title"] = "Manage Roles";
            Roles = _roleApplication.GetAll();
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Comment/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SM.Application.Contracts.Comment;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Comment
{
    public class IndexModel : PageModel
    {

        private readonly ICommentApplication _commentApplication;

        public IndexModel(ICommentApplication commentApplication)
        {
            _commentApplication = commentApplication;
        }

        [TempData]
        public string Message { get; set; }
        public List<CommentViewModel> Comments { get; set; }
        public SelectList ProductList { get; set; }


        public void OnGet(CommentSearchModel search)
        {
            @ViewData["title"] = "Comments";
            Comments = _commentApplication.Search(search);
        }

        public IActionResult OnPostConfirm(int Id)
        {
            var result = _commentApplication.Accept(Id);
            return new JsonResult(result);
        }
        public IActionResult OnPostDeny(int Id)
        {
            var result = _commentApplication.Deny(Id);
            return new JsonResult(result);
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/ProductPicture/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SM.Application.Contracts.Product;
using SM.Application.Contracts.ProductPicture;

namespace ServiceHost.Areas.Administrator.Pages.Shop.ProductPicture
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public ProductPictureSearchModel SearchModel { get; set; }
        public List<ProductPictureViewModel> ProductPictures { get; set; }
        public SelectList ProductList { get; set; }
        private readonly IProductPictureApplication _productPictureApplication;
        private readonly IProductApplication _productApplication;

        public IndexModel(IProductApplication productApplication,
            IProductPictureApplication productPictureApplication)
        {
            _productApplication = productApplication;
            _productPictureApplication = productPictureApplication;
        }

        public void OnGet(ProductPictureSearchModel searchModel)
        {
            ProductList = new SelectList(_productApplication.GetList(), "Id", "Name");
            @ViewData["title"] = "Manage Product Picture";
            ProductPictures = _productPictureApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateProductPicture();
            command.Products = _productApplication.GetList();
            @ViewData["title"] = "Add a new Picture";
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateProductPicture command)
        {
            command.Products = _productApplication.GetList();
            var result = _productPictureApplication.Create(command);
            return new JsonResult(result);

        }

        public IActionResult OnGetEdit(int id)
        {
            @ViewData["title"] = "Product Picture Management";
            var productPicture = _productPictureApplication.GetDetails(id);
            productPicture.Products = _productApplication.GetList();
            return Partial("./Edit", productPicture);
        }

        public JsonResult OnPostEdit(EditProductPicture command)
        {
            command.Products = _productApplication.GetList();
            var result = _productPictureApplication.Edit(command);
            return new JsonResult(result);
        }
        public IActionResult OnGetDelete(int Id)
        {
            var result = _productPictureApplication.Delete(Id);
            if (result.IsSucceeded)
            {
                Message = result.Message;
                return RedirectToPage("./Index");
            }
            else
            {
                Message = result.Message;
                return RedirectToPage("./Index");
            }
        }
        public IActionResult OnGetReactivate(int Id)
        {
            var result = _productPictureApplication.Reactivate(Id);
            if (result.IsSucceeded)
            {
                Message = result.Message;
                return RedirectToPage("./Index");
            }
            else
            {
                Message = result.Message;
                return RedirectToPage("./Index");
            }
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/ProductPicture/Create.cshtml
@model SM.Application.Contracts.ProductPicture.CreateProductPicture
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Add a new photo </h4>
</div>

<form asp-page-handler="Register" asp-page="./Index"
      data-callback=""
      method="post"
      data-action="Refresh"
      enctype="multipart/form-data"
      data-ajax="true">
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6 form-group">
                <label asp-for="ProductId"> Select Product </label>
                <select class="form-control" name="ProductId" asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id", "Name")'>
                    <option value="0"></option>
                </select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="col-md-6 from-group">
                <label asp-for="Picture">  </label>
                <input asp-for="Picture" type="file" class="form-control" accept="image/*"/>
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row from-group">
        <div clas="form-group col-md-12">
            <div class="col-md-6 from-group">
                <label asp-for="PictureTitle"></label>
                <input asp-for="PictureTitle" type="text" class="form-control" />
                <span asp-validation-for="PictureTitle" class="text-danger"></span>
            </div>
            <div class="col-md-6 from-group">
                <label asp-for="PictureAlt">  </label>
                <input asp-for="PictureAlt" type="text" class="form-control" />
                <span asp-validation-for="PictureAlt" class="text-danger"></span>
            </div>
        </div>
    </div>
    <input asp-for="Products" type="hidden"/>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Add
        </button>
    </div>
</form>

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/ProductPicture/Edit.cshtml
@model SM.Application.Contracts.ProductPicture.EditProductPicture
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Add a new photo </h4>
</div>

<form asp-page-handler="Edit" asp-page="./Index"
      data-callback=""
      method="post"
      data-action="Refresh"
      enctype="multipart/form-data"
      data-ajax="true">
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6 form-group">
                <label asp-for="ProductId"> Select Product </label>
                <select class="form-control" name="ProductId" asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id", "Name")'>
                    <option value="Id"></option>
                </select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="col-md-6 from-group">
                <label asp-for="Picture">  </label>
                <input asp-for="Picture" type="file" class="form-control" accept="image/*"/>
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row from-group">
        <div clas="form-group col-md-12">
            <div class="col-md-6 from-group">
                <label asp-for="PictureTitle"></label>
                <input asp-for="PictureTitle" type="text" class="form-control" />
                <span asp-validation-for="PictureTitle" class="text-danger"></span>
            </div>
            <div class="col-md-6 from-group">
                <label asp-for="PictureAlt">  </label>
                <input asp-for="PictureAlt" type="text" class="form-control" />
                <span asp-validation-for="PictureAlt" class="text-danger"></span>
            </div>
        </div>
    </div>
    <input asp-for="Id" type="hidden"/>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Save Changes
        </button>
    </div>
</form>

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/ProductPicture/Index.cshtml
@page
@using _0_Framework.Application
@model ServiceHost.Areas.Administrator.Pages.Shop.ProductPicture.IndexModel
@{

}


<div class='row'>
    <div class="col-sm-12">
        <h1 class="page-title text-dark"> @ViewData["title"] </h1>
        <p class="pull-right">
            <a id="showModal" href="#showmodal=@Url.Page("./Index", "Create")"
               class="btn btn-success wave-effect wave-light">
                <i class="fa fa-plus-circle"></i>
                Add a new Picture
            </a>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3> Search </h3>
            </div>
            <div class="panel-body">
                <form method="get" role="form" class="form-inline">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"> Filter by Product</label>
                        <select class="form-control" asp-items="Model.ProductList" name="ProductId" asp-for="SearchModel.ProductId">
                            <option value="0">
                                Please select a product
                            </option>
                        </select>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary waves-effect waves-light">Search</button>
                    </div>
                    <div class="form-group">
                        <a class="btn btn-purple waves-effect waves-light" asp-page="./Index"> Watch All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="panel-heading">
    <h3 class="panel-title">Products</h3>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <table id="myTable" class="display table-condensed table-bordered table-dark table-striped text-center col-md-12">
                <thead style="white-space: nowrap;">
                    <tr>
                        <th class="text-center">Product Id</th>
                        <th class="text-center">Picture</th>
                        <th class="text-center">Product Name</th>
                        <th class="text-center">Creation Time</th>
                        <th class="text-center">Deleted</th>
                        <th class="text-center">Modify</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ProductPictures)
                    {
                        <tr>
                            <td> @item.ProductId</td>
                            <td>
                                <img src="/Images/Site-Picture/@item.Product/@item.Picture" style="height: 100px; width: 100px;" />
                            </td>
                            <td> @item.Product</td>
                            <td> @item.CreationTime</td>
                            <td>
                                @if (item.IsRemoved)
                                {
                                    <i class="fa fa-close fa-2x text-danger"></i>
                                }
                                else
                                {
                                    <i class="fa fa-check fa-2x text-success"></i>
                                }
                            </td>

                            <td class="col-sm-1">
                                <a id="showModal"
                                   href="#showmodal=@Url.Page("./Index", "Edit", new {id = item.Id})"
                                   class="btn btn-warning waves-effect waves-light col-lg-12">
                                    <i class="fa fa-edit"></i> Modify
                                </a>
                                @if (@item.IsRemoved)
                                {
                                    <a class="btn btn-default waves-effect wave-light text-danger col-lg-12"
                                       asp-page="./Index" asp-page-handler="Reactivate" asp-route-id="@item.Id">
                                        <i class="fa fa-check"></i> Mark it as "Available"
                                    </a>
                                }
                                else
                                {
                                    <a class="btn btn-default waves-effect wave-light col-lg-12"
                                       asp-page="./Index" asp-page-handler="Delete" asp-route-id="@item.Id">
                                        <i class="fa fa-close"></i> Mark it as "Deleted"
                                    </a>
                                }

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



@section Scripts
{
    @if (TempData["Message"] != null)
    {
        if (TempData["Message"].ToString() == "Operation has been successfully proceeded.")
        {
            <script>
                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: 'Your work has been saved',
                    showConfirmButton: false,
                    timer: 1000
                })
            </script>
        }
        else
        {
            <script>
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: @TempData["Message"],
                    footer: '<a href="">Why do I have this issue?</a>'
                })
            </script>
        }

    }
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                language: { search: 'Search:', searchPlaceholder: "Search ..." }
            });
            $('input[type="search"]').css('border-width', '1px');
        })
    </script>
}