HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Account/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using AM.Application.Contracts;
using IM.Application.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SM.Application.Contracts;
using SM.Application.Contracts.Product;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public AccountSearchModel SearchModel { get; set; }
        public List<AccountViewModel> Accounts { get; set; }
        public SelectList RoleList { get; set; }
        private readonly IAccountApplication _accountApplication;
        public IndexModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            // RoleList = new SelectList(.GetList(), "Id", "Name");
            @ViewData["title"] = "Manage Accounts";
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {

            @ViewData["title"] = "Create a new Account";
            return Partial("./Create");
        }

        public JsonResult OnPostCreate(CreateAccount command)
        {
            var result = _accountApplication.Create(command);
            return new JsonResult(result);

        }

        public IActionResult OnGetEdit(long id)
        {
            @ViewData["title"] = "Account Management";
            var account = _accountApplication.GetDetail(id);
            return Partial("./Edit", account);
        }

        public JsonResult OnPostEdit(EditAccount command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var account = _accountApplication.getDetailforChangePassword(id);
            return Partial("./ChangePassword", account);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }


    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Account/Index.cshtml.cs
using System.Collections.Generic;
using AM.Application.Contracts.Account;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public AccountSearchModel SearchModel { get; set; }
        public List<AccountViewModel> Accounts { get; set; }
        public SelectList RoleList { get; set; }
        private readonly IAccountApplication _accountApplication;
        private readonly IRoleApplication _roleApplication;
        public IndexModel(IAccountApplication accountApplication,
            IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            RoleList = new SelectList(_roleApplication.GetAll(), "Id", "Name");
            @ViewData["title"] = "Manage Accounts";
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetRegister()
        {
            var command = new RegisterAccount
            {
                RoleList = _roleApplication.GetAll()
            };
            @ViewData["title"] = "Register a new Account";
            return Partial("./Register", command);
        }

        public JsonResult OnPostRegister(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            return new JsonResult(result);

        }

        public IActionResult OnGetEdit(long id)
        {
            @ViewData["title"] = "Account Management";
            var account = _accountApplication.GetDetail(id);
            account.RoleList = _roleApplication.GetAll();
            return Partial("./Edit", account);
        }

        public JsonResult OnPostEdit(EditAccount command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var account = _accountApplication.getDetailforChangePassword(id);
            return Partial("./ChangePassword", account);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }


    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Create.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Infrastructure;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        public List<SelectListItem> PermissionItems = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public CreateModel(IRoleApplication roleApplication,
            IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _exposers = permissionExposer;
        }

        public void OnGet()
        {
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermission = exposer.Exposer();
                foreach (var eachPermission in exposedPermission)
                {
                    var graoupName = new SelectListGroup
                    {
                        Name = eachPermission.Key
                    };
                    foreach (var permissionDetail in eachPermission.Value)
                    {
                        var item = new SelectListItem(permissionDetail.Name, permissionDetail.Code.ToString())
                        {
                            Group = graoupName
                        };
                        PermissionItems.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(CreateRole command)
        {

            var result = _roleApplication.Create(command);
            return RedirectToPage("Index");

        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public EditRole Role;
        public List<SelectListItem> PermissionItems = new List<SelectListItem>();
        public EditModel(IRoleApplication roleApplication,
            IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _exposers = permissionExposer;
        }

        public void OnGet(int id)
        {
            @ViewData["title"] = "Account Management";
            Role = _roleApplication.GetRole(id);
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermission = exposer.Exposer();
                foreach (var eachPermission in exposedPermission)
                {
                    var graoupName = new SelectListGroup
                    {
                        Name = eachPermission.Key
                    };
                    foreach (var permissionDetail in eachPermission.Value)
                    {
                        var item = new SelectListItem(permissionDetail.Name, permissionDetail.Code.ToString())
                        {
                            Group = graoupName
                        };
                        if (Role.MappedPermissions.Any(x => x.Code == permissionDetail.Code))
                            item.Selected = true;
                        PermissionItems.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(EditRole Role)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _roleApplication.Edit(Role);
            return RedirectToPage("Index");
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Index.cshtml.cs
using System.Collections.Generic;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public List<RoleViewModel> Roles { get; set; }
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
            @ViewData["title"] = "Manage Roles";
            Roles = _roleApplication.GetAll();
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Account/ChangePassword.cshtml
@model AM.Application.Contracts.Account.ChangePassword
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Edit </h4>
</div>

<form asp-page-handler="ChangePassword" asp-page="./Index"
      data-callback=""
      method="post"
      data-action="Refresh"
      data-ajax="true"
      >
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-12">
                <p> @Model.Email</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6">
                <label asp-for="Password"> Password </label>
                <input asp-for="Password" type="text" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="RePassword"> Retype Password </label>
                <input asp-for="RePassword" type="text" class="form-control" />
                <span asp-validation-for="RePassword" class="text-danger"></span>
            </div>
        </div>
    </div>

    <input type="hidden" asp-for="Id" value="@Model.Id" />
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Save Changes
        </button>
    </div>
</form>

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Account/Create.cshtml
@using Microsoft.EntityFrameworkCore
@model AM.Application.Contracts.Account.CreateAccount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Create a Account </h4>
</div>

<form asp-page-handler="Create" asp-page="./Index"
      data-callback=""
      method="post"
      data-action="Refresh"
      data-ajax="true"
      enctype="multipart/form-data">
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6">
                <label asp-for="Email"> Email </label>
                <input asp-for="Email" type="text" class="form-control"
                       />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="FullName"> FullName </label>
                <input asp-for="FullName" type="text" class="form-control"/>
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6">
                <label asp-for="UserId"> User Id </label>
                <input asp-for="UserId" type="text" class="form-control"
                />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="PhoneNumber"> PhoneNumber </label>
                <input asp-for="PhoneNumber" type="number" class="form-control"/>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-2 from-group">
                <label asp-for="RoleId"> Role </label>
                <select class="form-control" asp-for="RoleId" asp-items='new SelectList(Model.RoleList,"Id","Name")'>
                    <option value="0"></option>
                </select>
                <span asp-validation-for="RoleId" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label asp-for="ProfilePicture"> Picture </label>
            <input asp-for="ProfilePicture" type="file" class="form-control" accept="image/*"/>
            <span class="error"></span>
        </div>
    </div>
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-12 from-group">
                <label asp-for="Password"> Password </label>
                <input asp-for="Password" type="text" class="form-control"/>
                <span class="error"></span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Create
        </button>
    </div>
</form>

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Account/Edit.cshtml
@model AM.Application.Contracts.Account.EditAccount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Edit </h4>
</div>

<form asp-page-handler="Edit" asp-page="./Index"
      data-callback=""
      method="post"
      data-action="Refresh"
      data-ajax="true"
      enctype="multipart/form-data">
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6">
                <label asp-for="Email"> Email </label>
                <input asp-for="Email" type="text" class="form-control"
                />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="FullName"> FullName </label>
                <input asp-for="FullName" type="text" class="form-control"/>
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6">
                <label asp-for="UserId"> User Id </label>
                <input asp-for="UserId" type="text" class="form-control"
                />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="PhoneNumber"> PhoneNumber </label>
                <input asp-for="PhoneNumber" type="number" class="form-control"/>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-8 from-group">
                <label asp-for="RoleId"> Role </label>
                 <select class="form-control" asp-for="RoleId" asp-items='new SelectList(Model.RoleList,"Id", "Name")'>
                     <option value="0"></option>
                 </select>
                <span asp-validation-for="RoleId" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            @if (@Model.PictureString != null)
            {
                <div class="form-group col-md-12">
                    <span> Current Picture</span>
                    <img src="~/Images/ProfilePicture/@Model.PictureString" style="height: 100px; width: 100px;"/>
                </div>
            }
            <label asp-for="ProfilePicture"> Picture </label>
            <input asp-for="ProfilePicture" type="file" class="form-control" accept="image/*"/>
            @if (@Model.ProfilePicture == null)
            {
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            }
        </div>
        </div>

    <input type="hidden" asp-for="Id" value="@Model.Id" />
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Save Changes
        </button>
    </div>
</form>

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Account/Index.cshtml
@page
@model ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Account.IndexModel
@{

}


<div class='row'>
    <div class="col-sm-12">
        <h1 class="page-title text-dark"> @ViewData["title"] </h1>
        <p class="pull-right">
            <a id="showModal" href="#showmodal=@Url.Page("./Index", "Register")"
               class="btn btn-success wave-effect wave-light">
                <i class="fa fa-plus-circle"></i>
                Register a new Account
            </a>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3> Search </h3>
            </div>
            <div class="panel-body">
                <form method="get" role="form" class="form-inline">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.FullName"></label>
                        <input class="from-control" placeholder="Product Name"
                               asp-for="SearchModel.FullName" />
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Email"></label>
                        <input class="from-control" placeholder="Product Code"
                               asp-for="SearchModel.Email" />
                    </div>

                    @* <div class="form-group"> *@
                    @*     <label class="sr-only" asp-for="SearchModel.PhoneNumber"></label> *@
                    @*     <select class="form-control" asp-for="SearchModel.PhoneNumber" *@
                    @*             asp-items="Model.RoleList"> *@
                    @*         <option value="0"> *@
                    @*             Please select a role *@
                    @*         </option> *@
                    @*     </select> *@
                    @* </div> *@
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary waves-effect waves-light">Search</button>
                    </div>
                    <div class="form-group">
                        <a class="btn btn-purple waves-effect waves-light" asp-page="./Index"> Watch All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="panel-heading">
    <h3 class="panel-title">Products</h3>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <table id="myTable" class="display table-condensed table-bordered table-dark table-striped text-center col-md-12">
                <thead style="white-space: nowrap;">
                    <tr>
                        <th class="text-center">#</th>
                        <th class="text-center">Creation Date</th>
                        <th class="text-center">Full Name</th>
                        <th class="text-center">Email</th>
                        <th class="text-center">User Id</th>
                        <th class="text-center">Phone Number</th>
                        <th class="text-center">Picture</th>
                        <th class="text-center">Role</th>
                        <th class="text-center">Modify</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Accounts)
                    {
                        <tr>
                            <td> @item.Id</td>
                            <td> @item.CreationTime</td>
                            <td> @item.FullName</td>
                            <td> @item.Email</td>
                            <td> @item.UserId</td>
                            <td> @item.PhoneNumber</td>
                            <td>
                                <img src="~/Images/ProfilePicture/@item.ProfilePicture" style="height: 100px; width: 100px;" />
                            </td>
                            <td> @item.Role</td>
                            <td class="col-md-4">
                                <a id="showModal"
                                   href="#showmodal=@Url.Page("./Index", "Edit", new {id = item.Id})"
                                   class="btn btn-warning waves-effect waves-light col-md-4">
                                    <i class="fa fa-edit"></i> Modify
                                </a>
                                <a id="showModal"
                                   href="#showmodal=@Url.Page("./Index", "ChangePassword", new {id = item.Id})"
                                   class="btn btn-dark waves-effect waves-light col-md-8">
                                    <i class="fa fa-key"></i> Change Password
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



@section Scripts
{
    @if (TempData["Message"] != null)
    {
        if (TempData["Message"].ToString() == "Operation has been successfully proceeded.")
        {
            <script>
                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: 'Your work has been saved',
                    showConfirmButton: false,
                    timer: 1000
                })
            </script>
        }
        else
        {
            <script>
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: @TempData["Message"],
                    footer: '<a href="">Why do I have this issue?</a>'
                })
            </script>
        }

    }
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                language: { search: 'Search:', searchPlaceholder: "Search ..." }
            });
            $('input[type="search"]').css('border-width', '1px');
        })
    </script>
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Account/Register.cshtml
@using Microsoft.EntityFrameworkCore
@model AM.Application.Contracts.Account.RegisterAccount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Register a Account </h4>
</div>

<form asp-page-handler="Register" asp-page="./Index"
      data-callback=""
      method="post"
      data-action="Refresh"
      data-ajax="true"
      enctype="multipart/form-data">
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6">
                <label asp-for="Email"> Email </label>
                <input asp-for="Email" type="text" class="form-control"
                       />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="FullName"> FullName </label>
                <input asp-for="FullName" type="text" class="form-control"/>
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6">
                <label asp-for="UserId"> User Id </label>
                <input asp-for="UserId" type="text" class="form-control"
                />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="PhoneNumber"> PhoneNumber </label>
                <input asp-for="PhoneNumber" type="number" class="form-control"/>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-8 from-group">
                <label asp-for="RoleId"> Role </label>
                <select class="form-control" asp-for="RoleId" asp-items='new SelectList(Model.RoleList,"Id","Name")'>
                    <option value="0"></option>
                </select>
                <span asp-validation-for="RoleId" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label asp-for="ProfilePicture"> Picture </label>
            <input asp-for="ProfilePicture" type="file" class="form-control" accept="image/*"/>
            <span class="error"></span>
        </div>
    </div>
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-12 from-group">
                <label asp-for="Password"> Password </label>
                <input asp-for="Password" type="text" class="form-control"/>
                <span class="error"></span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Register
        </button>
    </div>
</form>