HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Account/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using AM.Application.Contracts;
using IM.Application.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SM.Application.Contracts;
using SM.Application.Contracts.Product;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public AccountSearchModel SearchModel { get; set; }
        public List<AccountViewModel> Accounts { get; set; }
        public SelectList RoleList { get; set; }
        private readonly IAccountApplication _accountApplication;
        public IndexModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            // RoleList = new SelectList(.GetList(), "Id", "Name");
            @ViewData["title"] = "Manage Accounts";
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {

            @ViewData["title"] = "Create a new Account";
            return Partial("./Create");
        }

        public JsonResult OnPostCreate(CreateAccount command)
        {
            var result = _accountApplication.Create(command);
            return new JsonResult(result);

        }

        public IActionResult OnGetEdit(long id)
        {
            @ViewData["title"] = "Account Management";
            var account = _accountApplication.GetDetail(id);
            return Partial("./Edit", account);
        }

        public JsonResult OnPostEdit(EditAccount command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var account = _accountApplication.getDetailforChangePassword(id);
            return Partial("./ChangePassword", account);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }


    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Account/Index.cshtml.cs
using System.Collections.Generic;
using AM.Application.Contracts.Account;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public AccountSearchModel SearchModel { get; set; }
        public List<AccountViewModel> Accounts { get; set; }
        public SelectList RoleList { get; set; }
        private readonly IAccountApplication _accountApplication;
        private readonly IRoleApplication _roleApplication;
        public IndexModel(IAccountApplication accountApplication,
            IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            RoleList = new SelectList(_roleApplication.GetAll(), "Id", "Name");
            @ViewData["title"] = "Manage Accounts";
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetRegister()
        {
            var command = new RegisterAccount
            {
                RoleList = _roleApplication.GetAll()
            };
            @ViewData["title"] = "Register a new Account";
            return Partial("./Register", command);
        }

        public JsonResult OnPostRegister(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            return new JsonResult(result);

        }

        public IActionResult OnGetEdit(long id)
        {
            @ViewData["title"] = "Account Management";
            var account = _accountApplication.GetDetail(id);
            account.RoleList = _roleApplication.GetAll();
            return Partial("./Edit", account);
        }

        public JsonResult OnPostEdit(EditAccount command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var account = _accountApplication.getDetailforChangePassword(id);
            return Partial("./ChangePassword", account);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }


    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Create.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Infrastructure;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        public List<SelectListItem> PermissionItems = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public CreateModel(IRoleApplication roleApplication,
            IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _exposers = permissionExposer;
        }

        public void OnGet()
        {
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermission = exposer.Exposer();
                foreach (var eachPermission in exposedPermission)
                {
                    var graoupName = new SelectListGroup
                    {
                        Name = eachPermission.Key
                    };
                    foreach (var permissionDetail in eachPermission.Value)
                    {
                        var item = new SelectListItem(permissionDetail.Name, permissionDetail.Code.ToString())
                        {
                            Group = graoupName
                        };
                        PermissionItems.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(CreateRole command)
        {

            var result = _roleApplication.Create(command);
            return RedirectToPage("Index");

        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public EditRole Role;
        public List<SelectListItem> PermissionItems = new List<SelectListItem>();
        public EditModel(IRoleApplication roleApplication,
            IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _exposers = permissionExposer;
        }

        public void OnGet(int id)
        {
            @ViewData["title"] = "Account Management";
            Role = _roleApplication.GetRole(id);
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermission = exposer.Exposer();
                foreach (var eachPermission in exposedPermission)
                {
                    var graoupName = new SelectListGroup
                    {
                        Name = eachPermission.Key
                    };
                    foreach (var permissionDetail in eachPermission.Value)
                    {
                        var item = new SelectListItem(permissionDetail.Name, permissionDetail.Code.ToString())
                        {
                            Group = graoupName
                        };
                        if (Role.MappedPermissions.Any(x => x.Code == permissionDetail.Code))
                            item.Selected = true;
                        PermissionItems.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(EditRole Role)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _roleApplication.Edit(Role);
            return RedirectToPage("Index");
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Index.cshtml.cs
using System.Collections.Generic;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public List<RoleViewModel> Roles { get; set; }
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
            @ViewData["title"] = "Manage Roles";
            Roles = _roleApplication.GetAll();
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Comment/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SM.Application.Contracts.Comment;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Comment
{
    public class IndexModel : PageModel
    {

        private readonly ICommentApplication _commentApplication;

        public IndexModel(ICommentApplication commentApplication)
        {
            _commentApplication = commentApplication;
        }

        [TempData]
        public string Message { get; set; }
        public List<CommentViewModel> Comments { get; set; }
        public SelectList ProductList { get; set; }


        public void OnGet(CommentSearchModel search)
        {
            @ViewData["title"] = "Comments";
            Comments = _commentApplication.Search(search);
        }

        public IActionResult OnPostConfirm(int Id)
        {
            var result = _commentApplication.Accept(Id);
            return new JsonResult(result);
        }
        public IActionResult OnPostDeny(int Id)
        {
            var result = _commentApplication.Deny(Id);
            return new JsonResult(result);
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/ProductCategories/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SM.Application.Contracts;
using SM.Infrastructure.Core;

namespace ServiceHost.Areas.Administrator.Pages.Shop.ProductCategories
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public ProductCategorySearchModel SearchModel { get; set; }
        public List<ProductCategoryViewModel> ProductCategories { get; set; }
        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductCategoryApplication productCategoryApplication)
        {
            _productCategoryApplication = productCategoryApplication;
        }
        [RequirePermission(ShopPermissions.SearchProductCategory)]
        public void OnGet(ProductCategorySearchModel searchModel)
        {
            @ViewData["title"] = "Manage Product Category";
            ProductCategories = _productCategoryApplication.Search(searchModel);
        }
        [RequirePermission(ShopPermissions.CreateProductCategory)]
        public IActionResult OnGetCreate()
        {
            @ViewData["title"] = "Register a Product Category";
            return Partial("./Create", new CreateProductCategory());
        }
        [RequirePermission(ShopPermissions.CreateProductCategory)]
        public JsonResult OnPostCreate(CreateProductCategory command)
        {
            var result = _productCategoryApplication.Create(command);
            return new JsonResult(result);

        }
        [RequirePermission(ShopPermissions.EditProductCategory)]
        public IActionResult OnGetEdit(int id)
        {
            @ViewData["title"] = "Product Category Management";
            var productCategory = _productCategoryApplication.GetDetails(id);
            return Partial("./Edit", productCategory);
        }
        [RequirePermission(ShopPermissions.EditProductCategory)]
        public JsonResult OnPostEdit(EditProductCategory command)
        {
            var result = _productCategoryApplication.Edit(command);
            return new JsonResult(result);
        }
        [RequirePermission(ShopPermissions.Deactivate)]
        public JsonResult OnPostDeactive(int Id)
        {
            var result = _productCategoryApplication.Deactivate(Id);
            return new JsonResult(result);
        }
        [RequirePermission(ShopPermissions.Deactivate)]
        public IActionResult OnPostReactive(int Id)
        {
            var result = _productCategoryApplication.Reactivate(Id);
            return new JsonResult(result);
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Slider/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SM.Application.Contracts.Product;
using SM.Application.Contracts.ProductPicture;
using SM.Application.Contracts.Slider;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Slider
{
    public class IndexModel : PageModel
    {
        public IndexModel(ISliderApplication sliderApplication)
        {
            _sliderApplication = sliderApplication;
        }

        [TempData]
        public string Message { get; set; }
        public List<SliderViewModel> Slider { get; set; }
        public SelectList ProductList { get; set; }
        private readonly ISliderApplication _sliderApplication;


        public void OnGet()
        {
            Slider = _sliderApplication.GetList();
            @ViewData["title"] = "Manage Slider";
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateSlider();
            @ViewData["title"] = "Add a new slider";
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateSlider command)
        {
            var result = _sliderApplication.Create(command);
            return new JsonResult(result);

        }

        public IActionResult OnGetEdit(int id)
        {
            @ViewData["title"] = "Slider Management";
            var slider = _sliderApplication.GetDetails(id);
            return Partial("./Edit", slider);
        }

        public JsonResult OnPostEdit(EditSlider command)
        {
            var result = _sliderApplication.Edit(command);
            return new JsonResult(result);
        }
        public IActionResult OnGetDelete(int Id)
        {
            var result = _sliderApplication.Delete(Id);
            if (result.IsSucceeded)
            {
                Message = result.Message;
                return RedirectToPage("./Index");
            }
            else
            {
                Message = result.Message;
                return RedirectToPage("./Index");
            }
        }
        public IActionResult OnGetReactivate(int Id)
        {
            var result = _sliderApplication.ReActivate(Id);
            if (result.IsSucceeded)
            {
                Message = result.Message;
                return RedirectToPage("./Index");
            }
            else
            {
                Message = result.Message;
                return RedirectToPage("./Index");
            }
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/ProductCategories/Create.cshtml
@model SM.Application.Contracts.CreateProductCategory
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"> <i class="fa fa-times-circle"></i> </button>
    <h4> Register a new category </h4>
</div>



<form asp-page-handler="Register" asp-page="./Index"
      data-callback=""
      method="post"
      data-action="Refresh"
      data-ajax="true"
      enctype="multipart/form-data">
        <div class="row">
            <div clas="form-group col-md-12">
                <div class="col-md-6">
                    <label asp-for="Name"> Name </label>
                    <input asp-for="Name" type="text" class="form-control"
                           onchange="makeSlug('Name', 'Slug')"/>
                    <span asp-validation-for="Name"  class="text-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Slug"> Slug </label>
                    <input asp-for="Slug" type="text" class="form-control"/>
                     <span asp-validation-for="Slug" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label asp-for="Picture"> Picture </label>
                <input asp-for="Picture" type="file" class="form-control" accept="image/*"
                        />
                <span class="error"></span>
            </div>
        </div>
        <div class="row">
            <div clas="form-group col-md-12">
                <div class="col-md-6">
                    <label asp-for="PictureAlt"> Picture Alt </label>
                    <input asp-for="PictureAlt" type="text" class="form-control"
                           />
                    <span class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="PictureTitle"> Picture Title </label>
                <input asp-for="PictureTitle" type="text" class="form-control"
                      />
                <span class="error"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label asp-for="Description"> Description </label>
                <textarea asp-for="Description" type="text" class="form-control"
                          onchange="fillField('Description', 'MetaDescription')" rows="3"></textarea>
                <span class="error"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label asp-for="Keyword"> Keyword </label>
                <input asp-for="Keyword" type="text" class="form-control" />
                <span asp-validation-for="Keyword" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label asp-for="MetaDescription"> Meta Description </label>
                <textarea asp-for="MetaDescription" type="text" class="form-control" rows="3"></textarea>
                 <span asp-validation-for="MetaDescription" class="text-danger"></span>
            </div>
        </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Register
        </button>
    </div>
</form>

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/ProductCategories/Edit.cshtml
@model SM.Application.Contracts.EditProductCategory
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"> <i class="fa fa-times-circle"></i> </button>
    <h4> Edit @Model.Name </h4>
</div>

<form asp-page-handler="Edit" asp-page="./Index"
      data-callback=""
      method="post"
      data-action="Refresh"
      data-ajax="true"
      enctype="multipart/form-data">
        <div class="row">
            <div clas="form-group col-md-12">
                <div class="col-md-6">
                    <label asp-for="Name"> Name </label>
                    <input asp-for="Name" type="text" class="form-control"
                           onchange="makeSlug('Name', 'Slug')"/>
                    <span class="error"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Slug"> Slug </label>
                    <input asp-for="Slug" type="text" class="form-control"/>
                    <span class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label asp-for="Picture"> Picture </label>
                <input asp-for="Picture" type="file" class="form-control" accept="image/*"
                        />
                <span class="error"></span>
            </div>
        </div>
        <div class="row">
            <div clas="form-group col-md-12">
                <div class="col-md-6">
                    <label asp-for="PictureAlt"> Picture Alt </label>
                    <input asp-for="PictureAlt" type="text" class="form-control"
                           />
                    <span class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <label asp-for="PictureTitle"> Picture Title </label>
                <input asp-for="PictureTitle" type="text" class="form-control"
                      />
                <span class="error"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label asp-for="Description"> Description </label>
                <textarea asp-for="Description" type="text" class="form-control"
                          onchange="fillField('Description', 'MetaDescription')" rows="3"></textarea>
                <span class="error"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label asp-for="Keyword"> Keyword </label>
                <input asp-for="Keyword" type="text" class="form-control" />
                <span class="error"></span>
            </div>
        </div>
    <div class="row">
        <div class="form-group col-md-12">
            <label asp-for="MetaDescription"> Meta Description </label>
            <textarea asp-for="MetaDescription" type="text" class="form-control" rows="3"></textarea>
            <span class="error"></span>
        </div>
    </div>
    <input type="hidden" asp-for="Id" />
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Save Changes
        </button>
    </div>
</form>

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/ProductCategories/Index.cshtml
@page
@using _0_Framework.Application
@using System.Linq
@using SM.Infrastructure.Core

@model ServiceHost.Areas.Administrator.Pages.Shop.ProductCategories.IndexModel
@{

}


<div class='row'>
    <div class="col-sm-12">
        <h1 class="page-title text-dark"> @ViewData["title"] </h1>
        <p class="pull-right">
            <a id="showModal" href="#showmodal=@Url.Page("./Index", "Create")" permission="@ShopPermissions.CreateProductCategory"
               class="btn btn-success wave-effect wave-light">
                <i class="fa fa-plus-circle"></i>
                Register a new Category
            </a>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3> Search </h3>
            </div>
            <div class="panel-body">
                <form method="get" role="form" class="form-inline" permission="@ShopPermissions.SearchProductCategory">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Name" ></label>
                        <input class="from-control" placeholder="Product Category Name"
                               asp-for="SearchModel.Name" />
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary waves-effect waves-light">Search</button>
                    </div>
                    <div class="form-group">
                        <a class="btn btn-purple waves-effect waves-light" asp-page="./Index"> Watch All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="panel-heading">
    <h3 class="panel-title">Product Categories</h3>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <table id="myTable" class="display table-condensed table-bordered table-dark table-striped text-center col-md-12">
                <thead class="wrapper" id="thead">
                    <tr>
                        <th class="text-center">#</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Creation Time</th>
                        <th class="text-center">Picture</th>
                        <th class="text-center">No. Register Products</th>
                        <th class="text-center">Modify</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ProductCategories)
                    {
                        <tr>
                            <td> @item.Id</td>
                            <td> @item.Name</td>
                            <td> @item.CreationDate</td>
                            <td>
                                <img src="~/Images/@item.Name/@item.Picture" style="height: 100px; width: 100px;" />
                            </td>
                            <td> @item.ProductCount</td>
                            <td class="col-md-2" >
                                <a id="showModal" permission="@ShopPermissions.EditProductCategory"
                                   href="#showmodal=@Url.Page("./Index", "Edit", new {id = item.Id})"
                                   class="btn btn-warning waves-effect waves-light col-md-6">
                                    <i class="fa fa-edit"></i> Modify
                                </a>
                                @if (@item.IsActive)
                                {
                                    <form asp-page-handler="Deactive" asp-page="./Index" data-callback="" permission="@ShopPermissions.Deactivate"
                                          method="post" data-action="Refresh" data-ajax="true">
                                        <input type="hidden" id="Id" name="Id" value="@item.Id"/>
                                        <button id="submitModal" type="submit" class="btn btn-default waves-effect wave-light col-md-6">
                                            <i class="fa fa-toggle-on"></i>
                                        </button>
                                    </form>

                                }
                                else
                                {
                                    <form asp-page-handler="Reactive" asp-page="./Index" data-callback="" permission="@ShopPermissions.Reactivate"
                                          method="post" data-action="Refresh" data-ajax="true">
                                        <input type="hidden" id="Id" name="Id" value="@item.Id"/>
                                        <button id="submitModal" type="submit" class="btn btn-default waves-effect wave-light col-md-6">
                                            <i class="fa fa-toggle-off"></i>
                                        </button>
                                    </form>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



@section Scripts
{

    <script>
        var thead = document.getElementById('thead');
        thead.scrollIntoView({ behavior: 'smooth', block: 'start' });
        $(document).ready(function () {


            $('#myTable').DataTable({
                language: { search: 'Search:', searchPlaceholder: "Search ..."}
            });
            $('input[type="search"]').css('border-width', '1px');
        })
    </script>
}