HomeAppliance/ServiceHost/Areas/Administrator/Pages/Inventory/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Application;
using DM.Application.Contracts;
using DM.Application.Contracts.EndUser;
using IM.Application.Contracts;
using IM.Infrustructure.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SM.Application.Contracts.Product;

namespace ServiceHost.Areas.Administrator.Pages.Inventory
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public List<InventoryViewModel> Inventory { get; set; }
        public InventorySearchModel SearchModel { get; set; }
        public List<EndUserViewModel> Discounts { get; set; }
        public SelectList ProductList { get; set; }
        private readonly IProductApplication _productApplication;
        private readonly IInventoryApplication _inventoryApplication;

        public IndexModel(IProductApplication productApplication,
            IInventoryApplication inventoryApplication)
        {
            _productApplication = productApplication;
            _inventoryApplication = inventoryApplication;
        }
        [RequirePermission(InventoryPermissions.Search)]
        public void OnGet(InventorySearchModel searchModel)
        {
            ProductList = new SelectList(_productApplication.GetList(), "Id", "Name");
            @ViewData["title"] = "Manage Inventory";
            Inventory = _inventoryApplication.Search(searchModel);
        }
        [RequirePermission(InventoryPermissions.Create)]
        public IActionResult OnGetCreate()
        {
            var command = new CreateInventory();
            command.ProductList = _productApplication.GetList();
            @ViewData["title"] = "Register a new Inventory";

            return Partial("./Create", command);
        }
        [RequirePermission(InventoryPermissions.Create)]
        public JsonResult OnPostCreate(CreateInventory command)
        {
            var result = _inventoryApplication.Create(command);
            return new JsonResult(result);

        }
        [RequirePermission(InventoryPermissions.Edit)]
        public IActionResult OnGetEdit(int id)
        {
            @ViewData["title"] = "Inventory Management";
            var inventory = _inventoryApplication.GetDetail(id);
            inventory.ProductList = _productApplication.GetList();
            return Partial("./Edit", inventory);
        }
        [RequirePermission(InventoryPermissions.Edit)]
        public JsonResult OnPostEdit(EditInventory command)
        {
            var result = _inventoryApplication.Edit(command);
            return new JsonResult(result);
        }
        [RequirePermission(InventoryPermissions.Incremenet)]
        public IActionResult OnGetIncrement(int id)
        {
            var inventory = new IncrementInventory()
            {
                InventoryId = id
            };
            return Partial("./Increment", inventory);
        }
        [RequirePermission(InventoryPermissions.Incremenet)]
        public JsonResult OnPostIncrement(IncrementInventory command)
        {
            var result = _inventoryApplication.Increment(command);
            return new JsonResult(result);
        }
        [RequirePermission(InventoryPermissions.Decrement)]
        public IActionResult OnGetDecrement(int Id)
        {
            var inventory = new DecrementInventory()
            {
                InventoryId = Id
            };
            return Partial("./Decrement", inventory);
        }
        [RequirePermission(InventoryPermissions.Decrement)]
        public JsonResult OnPostDecrement(DecrementInventory command)
        {
            var result = _inventoryApplication.Decrement(command);
            return new JsonResult(result);
        }
        [RequirePermission(InventoryPermissions.GetOperationsLogs)]
        public IActionResult OnGetLog(int Id)
        {
            var inventory = _inventoryApplication.GetOperationLogs(Id);
            return Partial("./Log", inventory);
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Create.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Infrastructure;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        public List<SelectListItem> PermissionItems = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public CreateModel(IRoleApplication roleApplication,
            IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _exposers = permissionExposer;
        }

        public void OnGet()
        {
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermission = exposer.Exposer();
                foreach (var eachPermission in exposedPermission)
                {
                    var graoupName = new SelectListGroup
                    {
                        Name = eachPermission.Key
                    };
                    foreach (var permissionDetail in eachPermission.Value)
                    {
                        var item = new SelectListItem(permissionDetail.Name, permissionDetail.Code.ToString())
                        {
                            Group = graoupName
                        };
                        PermissionItems.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(CreateRole command)
        {

            var result = _roleApplication.Create(command);
            return RedirectToPage("Index");

        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Shop/Accounts/Role/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AM.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Accounts.Role
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public EditRole Role;
        public List<SelectListItem> PermissionItems = new List<SelectListItem>();
        public EditModel(IRoleApplication roleApplication,
            IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _exposers = permissionExposer;
        }

        public void OnGet(int id)
        {
            @ViewData["title"] = "Account Management";
            Role = _roleApplication.GetRole(id);
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermission = exposer.Exposer();
                foreach (var eachPermission in exposedPermission)
                {
                    var graoupName = new SelectListGroup
                    {
                        Name = eachPermission.Key
                    };
                    foreach (var permissionDetail in eachPermission.Value)
                    {
                        var item = new SelectListItem(permissionDetail.Name, permissionDetail.Code.ToString())
                        {
                            Group = graoupName
                        };
                        if (Role.MappedPermissions.Any(x => x.Code == permissionDetail.Code))
                            item.Selected = true;
                        PermissionItems.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(EditRole Role)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _roleApplication.Edit(Role);
            return RedirectToPage("Index");
        }
    }
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Inventory/Create.cshtml
@model IM.Application.Contracts.CreateInventory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Register a Inventory </h4>
</div>

<form asp-page-handler="Create" asp-page="./Index" data-callback=""
      method="post" data-action="Refresh" data-ajax="true">
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6 form-group">
                <label asp-for="ProductId"> Select Product </label>
                <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.ProductList, "Id", "Name")'>
                    <option value=""></option>
                </select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="UnitPrice"></label>
                <input asp-for="UnitPrice" type="number" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Register
        </button>
    </div>
</form>


HomeAppliance/ServiceHost/Areas/Administrator/Pages/Inventory/Decrement.cshtml
@model IM.Application.Contracts.DecrementInventory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Reduce from Inventory </h4>
</div>

<form asp-page-handler="Decrement" asp-page="./Index" data-callback=""
      method="post" data-action="Refresh" data-ajax="true">
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6 form-group">
                <label asp-for="Count"></label>
                <input asp-for="Count" type="number" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="col-md-6 form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" type="text" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
    </div>

    <input asp-for="InventoryId" type="hidden" />
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Save Changes
        </button>
    </div>
</form>

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Inventory/Edit.cshtml
@model IM.Application.Contracts.EditInventory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Edit </h4>
</div>

<form asp-page-handler="Edit" asp-page="./Index" data-callback=""
      method="post" data-action="Refresh" data-ajax="true">
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6 form-group">
                <label asp-for="ProductId"> Select Product</label>
                <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.ProductList, "Id", "Name")'>
                    <option value="Model.ProductId"></option>
                </select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="UnitPrice"></label>
                <input asp-for="UnitPrice" type="number" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
        </div>
    </div>

    <input asp-for="Id" type="hidden" />
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Save Changes
        </button>
    </div>
</form>

<script>
    
        
    
</script>

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Inventory/Increment.cshtml
@model IM.Application.Contracts.IncrementInventory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Increase the Inventory </h4>
</div>

<form asp-page-handler="Increment" asp-page="./Index" data-callback=""
      method="post" data-action="Refresh" data-ajax="true">
    <div class="row">
        <div clas="form-group col-md-12">
            <div class="col-md-6 form-group">
                <label asp-for="Count"></label>
                <input asp-for="Count" type="number" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="col-md-6 form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" type="text" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
    </div>

    <input asp-for="InventoryId" type="hidden" />
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"> Close </button>
        <button id="submitModal" type="submit" class="btn btn-inverse waves-effect waves-light">
            <i class="fa fa-save"></i>
            Save Changes
        </button>
    </div>
</form>

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Inventory/Index.cshtml
@page
@using _0_Framework.Application
@using IM.Infrustructure.Core
@model ServiceHost.Areas.Administrator.Pages.Inventory.IndexModel
@{

}


<div class='row'>
    <div class="col-sm-12">
        <h1 class="page-title text-dark"> @ViewData["title"] </h1>
        <p class="pull-right">
            <a id="showModal" href="#showmodal=@Url.Page("./Index", "Create")"
               class="btn btn-success wave-effect wave-light">
                <i class="fa fa-plus-circle"></i>
                Register a Inventory
            </a>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3> Search </h3>
            </div>
            <div class="panel-body">
                <form method="get" role="form" class="form-inline" autocomplete="off">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                        <select class="form-control" asp-for="SearchModel.ProductId" asp-items="@Model.ProductList">
                            <option value="0">
                                Select a product
                            </option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="SearchModel.IsInStock"> Search out of stock Items</label>
                        <input type="checkbox" asp-for="SearchModel.IsInStock" />
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary waves-effect waves-light">Search</button>
                    </div>
                    <div class="form-group">
                        <a class="btn btn-purple waves-effect waves-light" asp-page="./Index"> Watch All </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="panel-heading">
    <h3 class="panel-title">Products</h3>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <table id="myTable" class="display table-condensed table-bordered table-dark table-striped text-center col-md-12">
                <thead style="white-space: nowrap;">
                    <tr>
                        <th class="text-center">Product Id</th>
                        <th class="text-center">Product Name</th>
                        <th class="text-center">Unit Price</th>
                        <th class="text-center">Current Count</th>
                        <th class="text-center">Modify</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Inventory)
                    {
                        <tr>
                            <td> @item.ProductId</td>
                            <td> @item.ProductName</td>
                            <td> @item.UnitPrice</td>
                            <td> @item.CurrentCount</td>
                            <td class="col-sm-4">
                                <a permission="@InventoryPermissions.Edit"
                                    id="showModal" href="#showmodal=@Url.Page("./Index", "Edit", new {Id = item.Id})"
                                   class="btn btn-warning waves-effect waves-light">
                                    <i class="fa fa-edit"></i> Modify
                                </a>
                                <a id="showModal" href="#showmodal=@Url.Page("./Index", "Increment", new {Id = item.Id})"
                                   class="btn btn-success waves-effect waves-light">
                                    <i class="fa fa-level-up"></i> Increase
                                </a>
                                <a id="showModal" href="#showmodal=@Url.Page("./Index", "Decrement", new {Id = item.Id})"
                                   class="btn btn-danger waves-effect waves-light">
                                    <i class="fa fa-level-down"></i> Reduce
                                </a>
                                <a id="showModal" href="#showmodal=@Url.Page("./Index", "Log", new {Id = item.Id})"
                                   class="btn btn-default waves-effect waves-light"
                                   onclick="$('.modal-dialog').css('width','60%')">
                                    <i class="fa fa-history"></i> Log
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



@section Scripts
{

    @if (TempData["Message"] != null)
    {
        if (TempData["Message"].ToString() == "Operation has been successfully proceeded.")
        {
            <script>
                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: 'Your work has been saved',
                    showConfirmButton: false,
                    timer: 1000
                })
            </script>
        }
        else
        {
            <script>
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: @TempData["Message"],
                    footer: '<a href="">Why do I have this issue?</a>'
                })
            </script>
        }

    }
    <script>

        $(window).on('hidden.bs.modal', function () {
            $(".modal-dialog").css("width", "600px");
        })


    </script>
}

HomeAppliance/ServiceHost/Areas/Administrator/Pages/Inventory/Log.cshtml
@model List<IM.Application.Contracts.InventoryOperationLog>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <i class="fa fa-times-circle"></i>
    </button>
    <h4> Inventory History </h4>
</div>

<div>
    <table class="table table-bordered table-condensed text-center">
        <thead>
        <tr>
            <th class="text-center"> Id</th>
            <th class="text-center"> Operation Time</th>
            <th class="text-center"> Current Stock</th>
            <th class="text-center"> Operator Id</th>
            <th class="text-center"> Order Id</th>
            <th class="text-center"> Description </th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr class="text-white"
                style="@(item.OperationType ? "background-color:rgba(133,226,133,0.8); color: black"
                           : "background-color: rgba(212,50,50,0.8)" )">
                <td>@item.Id</td>
                <td>@item.OperationTime</td>
                <td>@item.CurrentStock</td>
                <td>@item.OperatorId</td>
                <td>@item.OrderId</td>
                <td>@item.Description</td>
            </tr>
        }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function() {
//        $("table").css("border", "solid black 1px");
//        $("table").css("border-radius", "5px");
//        $("td").css("border", "solid black 1px");
//        $("td").css("color", "black");
//        $("th").css("border", "solid black 1px");
    })
</script>